# syntax=docker/dockerfile:1
FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-venv \
        python3-pip \
        python3-setuptools && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/StaticJinjaPlus

ADD --checksum=sha256:30d9424df1eddb73912b0e2ad5375fa2c876c8e30906bec91952dfb75dcf220b \
https://github.com/MrDave/StaticJinjaPlus/archive/refs/tags/0.1.1.tar.gz /tmp/app.tar.gz

RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /opt/StaticJinjaPlus && rm /tmp/app.tar.gz

RUN python3.12 -m venv venv && \
    ./venv/bin/python -m pip install --no-cache-dir -r requirements.txt

ENV PATH="/opt/StaticJinjaPlus/venv/bin:$PATH"

CMD ["python","main.py","--srcpath","templates_example","--outpath","./build"]