# syntax=docker/dockerfile:1
FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /opt/StaticJinjaPlus

RUN git clone --depth 1 https://github.com/MrDave/StaticJinjaPlus.git \
    /opt/StaticJinjaPlus \
    && rm -rf /opt/StaticJinjaPlus/.git

RUN pip install -r requirements.txt

CMD ["python","main.py","--srcpath","templates_example","--outpath","./build"]